#%RAML 1.0
title: Client process API
version: 1.0
mediaType: application/json
baseUri: http://localhost:8081/api/process/clients
protocols: [ HTTP, HTTPS ]
types:
  Client:
    type: !include datatypes/client-datatypes.raml
  Error:
    type: !include errormessages/error-messages.raml



/:
  
  get:
    queryParameters:
      firstName:
        type: string
        required: false
        description: Fetch the client details based on firstName
      lastName:
        type: string
        required: false
        description: Fetch the client details based on lastName
      position:
        type: string
        required: false
        description: Fetch the client details based on position
      state:
        type: string
        required: false
        description: Fetch the client details based on state
      city:
        type: string
        required: false
        description: Fetch the client details based on city
      zipcode:
        type: string
        required: false
        description: Fetch the client details based on zipcode
      name:
        type: string
        required: false
        description: Fetch the client details based on name
      pocId:
        type: string
        required: false
        description: Fetch the client details based on pocId(person id)
    responses:
      200:
        body:
          application/json:
            type: Client[]

      400:
        description: If the request is with invalid parameters or incorrect and server could not understand it
        body:
          application/json:
            type: Error
            example: { "message" : "Bad Request", "code" : 400 }

  post:
    body:
      application/json:
        type: Client
        example: !include examples/client-example.json
    responses:
      201:
        headers:
          Location:
            displayName: Location
            type: string
            description: URI pointing to the location of the newly created client
            example: http://localhost:8081/api/process/clients/123/5573
            required: true
      409:
        description: When you try to post the same record again
        body:
          application/json:
            type: Error
            example: { "message" : "Conflict detected while inserting the record", "code" : 409 }
      400:
        description: If the request is with invalid parameters or incorrect and server could not understand it
        body:
          application/json:
            type: Error
            example: { "message" : "Bad request", "code" : 400 }
      415:
        description: If media type of the request body is different
        body:
          application/json:
            type: Error
            example: { "message" : "Unsupported media type", "code" : 415 }


/{personId}/{customerId}:
  displayName: personId and customerId
  description: Fetch the client information for the given personId and customerId
  uriParameters:
    personId:
      type: integer
      example: 10
      required: true
    customerId:
      type: integer
      example: 12
      required: true
  get:
    headers:
        If-None-Match:
          type: string
          description: |
             The request will be processed only if the eventually existing resource's ETag doesn't match the value.
          example: bfc13a64729c4290ef5b2c2730249c88ca92d82d
    responses:
      200:
        body:
          application/json:
            type: Client
            example: !include examples/client-example.json
        headers:
            ETag:
              displayName: ETag
              description: The current version of the resource
              type: string
              example: c7493-d7-a6b64d37f6cc3
      400:
        description: If the request is with invalid parameters or incorrect and server could not understand it 
        body:
          application/json:
            type: Error
            example: { "message" : "Bad request", "code" : 400 }
      304:
          description: If the value you send in If-None-Match matches with resource's ETag, you have the latest record
          body:
           application/json:
            type: Error
            example: { "message" : "Not Modified", "code" : 304 }      
      404:
        description: If there is no record found
        body:
          application/json:
            type: Error
            example: { "message" : "Resource not found", "code" : 404 }
  delete:
    description: To delete a particular Client
    responses:
      200:
        description: "Client has been successfully deleted!"
      400:
        description: If the request is with invalid parameters or incorrect and server could not understand it
        body:
          application/json:
            type: Error
            example: { "message" : "Bad request", "code" : 400 }
      404:
        description: if there is no record found
        body:
          application/json:
            type: Error
            example: { "message" : "Resource not found", "code" : 404 }
  patch:
    description: Update a record
    headers:
      If-Match:
          type: string
          description: |
            defines a precondition for updating the resource only if the versions match that header
          example: c7493-d7-a6b64d37f6cc3
    body:
      application/json:
        type: Client
        example: !include examples/client-example.json
    responses:
      204:
        description: "The Client has been successfully updated!"
        headers:
            ETag:
              displayName: ETag
              description: The current version of the resource
              type: string
              example: c7493-d7-a6b64d37f6cc3
      400:
        description: If the request is with invalid parameters or incorrect and server could not understand it
        body:
          application/json:          
            type: Error
            example: { "message" : "Bad request", "code" : 400 }
      404:
        description: If there is no record found
        body:
          application/json:
            type: Error
            example: { "message" : "Resource not found", "code" : 404 }
      412:
          description: If If-Match value doesn't match with resource's etag, you need to get latest version of the record
          headers:
            ETag:
              displayName: ETag
              description: The new version of the resource
              type: string
              example: c7493-d7-a6b64d37f6cc3
          body:
            application/json:
              type: Error
              example: { "message" : "Failed to modify. The resource has been modified by other process. please use GET /Clients/123 to retrieve the latest version of the resource.", "code" : 412 }
