#%RAML 1.0 DataType

type: object
properties: 
  name:
    type: string
    required: false
  hq_address_id:
    type: number
    required: false
  alt_address_id:
    type: number
    required: false
  billing_email:
    type: string
    required: false
  poc_id:
    type: number
    required: false
  notes:
    type: string
    required: false
example: |
          {
             "name": "name",
             "hq_address_id": 1255,
             "alt_address_id": 741,
             "billing_email": "sdasda@sss.com",
             "poc_id": 7899,
             "notes": "notes sd werwe"
          }
  