#%RAML 1.0 DataType
type: object
properties:
      client:
        type: !include client-datatypes.raml
        required: false
      contract:
        type: !include contract-datatypes.raml
        required: false
      offers:
        type: !include offer-datatype.raml
        required: false
