#%RAML 1.0 DataType
type: object
properties: 
  person_id:
    required: false
  first_name:
    required: false
  last_name:
    required: false
  phone_number: 
    required: false
  email:
    required: false
  person_notes: 
    required: false
  customer_id:
    required: false
  customer_name:
    required: false
  hq_address_id:
    required: false
  alt_address_id:
    required: false
  billing_email:
    required: false
  customer_notes:
    required: false
  line_1:
    required: false
  line_2:
    required: false
  state:
    required: false
  city:
    required: false
  zip_code:
    required: false
  contract_name:
    required: false
  contract_description:
    required: false
  sow:
    required: false
  entitlement_update_list:
    required: false
  start_date:
    required: false
  end_date:
    required: false
  product_id:
    required: false
  product_name:
    required: false
  product_description:
    required: false
  product_entitlements:
    required: false