#%RAML 1.0 DataType

description: 'The Contract object'
type: object
properties:
    id: 
      description: 'the unique id for this contract' 
      minimum: 1 
      example: 123
      type: number
      required: false
    contract_name: 
      description: 'The name used to identify this contract'
      minLength: 1
      example: 'The Date Contract with Company'
      type: string
      required: false
    contract_description:
      description: 'Gives more details about this contract'
      example: 'This contract was made by Employee on Date to cover Details about More Details.'
      type: string
      required: false
    type:
      description: 'The type of contract'
      example: 'SOW'
      required: false
    status:
      description: 'The status of the contract'
      example: 'Open'
      required: false
    customer_id:
      description: 'The identifier for the customer this contract applies to'
      example: 123
      type: number
      required: false
    product_id:
      description: 'The identifier for the product this contract provides to the customer.'
      example: 123
      type: number
      required: false
    escalation_contact_id:
      description: 'The contact identifier for who to contact about changing the details of this contract.'
      minimum: 1
      default: 123
      example: 123
      type: number
      required: false
    entitlement_update_list:
      description: 'A list of ids of entitlements that are specific to this contract, differing from the default product.'
      type: string
      example: 11,12,14
      required: false
    start_date:
      description: 'The date this contract begins'
      type: string
      example: 2017-06-30
      required: false
    end_date:
      description: 'The date this contract ends'
      type: string
      example: 2019-06-30
      required: false
