type: object
properties:
    id: 
      type: number
      required: true
    name:
      type: string
      required: false
    description:
      type: string
      required: false
    type:
      type: string
      required: false
    value:
      type: number
      required: false