type: object
properties:
    entitlement_id: {type: number}
    entitlement_name: {type: string}
    entitlement_description: {type: string}
    product_id: {type: number}
    product_name: {type: string}
    product_description: {type: string}
    prod_entitlement_1: {type: number}
    prod_entitlement_2: {type: number}
    prod_entitlement_3: {type: number}
    prod_entitlement_4: {type: number}
    prod_entitlement_5: {type: number}
    prod_entitlement_6: {type: number}
    prod_entitlement_7: {type: number}
    prod_entitlement_8: {type: number}
    prod_entitlement_9: {type: number}
    prod_entitlement_10: {type: number}
    contract_id: {type: number}
    contract_name: {type: string}
    contract_description: {type: string}
    SOW: {type: string}
    customer_id: {type: number}
    escalation_contact_id: {type: number}
    entitlement_update_list: {type: string}
    start_date: {type: string}
    end_date: {type: string}
