type: object
properties:
    id: {type: number}
    name: {type: string}
    description: {type: string}
    entitlement_1: {type: number}
    entitlement_2: {type: number}
    entitlement_3: {type: number}
    entitlement_4: {type: number}
    entitlement_5: {type: number}
    entitlement_6: {type: number}
    entitlement_7: {type: number}
    entitlement_8: {type: number}
    entitlement_9: {type: number}
    entitlement_10: {type: number}
