#%RAML 1.0 DataType
type: object
properties:
    product_id:
      type: number
      required: false
    product_name: 
      type: string
      required: false
    product_description: 
      type: string
      required: false
    entitlements:
      type: entitlement[]
      required: false